#!/bin/sh

cd $FOAM_HGS/fieldPorosityModel
wmake libso

cd $FOAM_HGS/radiationModels
wmake libso

cd $FOAM_HGS/thermophysicalModels
./Allwmake

cd $FOAM_HGS/pyrolysisModels
wmake libso

cd $WM_PROJECT_USER_DIR/applications/biomassGasificationFoam
wmake
