#!/bin/sh

source ./porousGasificationMediaDirectories

mkdir -p $FOAM_HGS

cp -r utilities $WM_PROJECT_USER_DIR/applications/
cp -r porousGasificationFoam $WM_PROJECT_USER_DIR/applications/
cp -r porousGasificationMedia/fieldPorosityModel $FOAM_HGS/
cp -r porousGasificationMedia/thermophysicalModels $FOAM_HGS/
cp -r porousGasificationMedia/pyrolysisModels $FOAM_HGS/
cp -r porousGasificationMedia/radiationModels $FOAM_HGS/
cp install $FOAM_HGS/

./Allwmake
